### ISSUE TITLE
Error when running on Linux ARM64

### ISSUE THREAD

**Issue by cantalupo555** [G-Ray/pikatorrent#128]
**Never include info about copyrighted materials!**

**Describe the bug**
Hello, I am getting this error when running.

**To Reproduce**
```
./pikatorrent 
[129456:1208/234523.080543:ERROR:web_contents_preferences.cc(243)] preload script must have absolute path.
(node:129456) UnhandledPromiseRejectionWarning: Error: /home/cantalupo/Downloads/pikatorrent-linux-arm64/resources/app/node_modules/@pikatorrent/node/node_modules/wrtc/build/Release/wrtc.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2131)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/cantalupo/Downloads/pikatorrent-linux-arm64/resources/app/node_modules/@pikatorrent/node/node_modules/wrtc/lib/binding.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
(Use `pikatorrent --trace-warnings ...` to show where the warning was created)
(node:129456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:129456) UnhandledPromiseRejectionWarning: Error: /home/cantalupo/Downloads/pikatorrent-linux-arm64/resources/app/node_modules/@pikatorrent/node/node_modules/wrtc/build/Release/wrtc.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2131)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/cantalupo/Downloads/pikatorrent-linux-arm64/resources/app/node_modules/@pikatorrent/node/node_modules/wrtc/lib/binding.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
(node:129456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Error occurred in handler for 'transmission:request': TypeError: Cannot read properties of undefined (reading 'transmission')
    at /home/cantalupo/Downloads/pikatorrent-linux-arm64/resources/app/src/index.js:205:13
    at new Promise (<anonymous>)
    at handleTransmissionRequest (/home/cantalupo/Downloads/pikatorrent-linux-arm64/resources/app/src/index.js:204:10)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)

```

**Platform:**
Linux ARM64 - Ubuntu 22.04

**Comment by G-Ray** [comment]
So this should be fixed with https://github.com/G-Ray/pikatorrent/pull/121 now, thank you for you testing feedback @cantalupo555
