### ISSUE TITLE
Replace wrtc with a better maintained lib

### ISSUE THREAD

**Issue by G-Ray** [G-Ray/pikatorrent#130]
`wrtc` is not maintained anymore.

Maybe ? https://github.com/murat-dogan/node-datachannel

**Comment by G-Ray** [comment]
Tried node-datachannel, it work great between with a client, but connection fails with `react-native-webrtc` on Android:

```
Error: libdatachannel error while adding remote description: Invalid ICE settings from remote SDP
    at _RTCPeerConnection.setRemoteDescription (file:///var/home/gbonneville/src/pikatorrent/packages/node/node_modules/node-datachannel/polyfill/RTCPeerConnection.js:458:30)
    at Peer.signal (/var/home/gbonneville/src/pikatorrent/packages/node/node_modules/simple-peer/index.js:210:16)
    at file:///var/home/gbonneville/src/pikatorrent/packages/node/dist/lib/websocket.js:56:22
    at Generator.next (<anonymous>)
    at file:///var/home/gbonneville/src/pikatorrent/packages/node/dist/lib/websocket.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///var/home/gbonneville/src/pikatorrent/packages/node/dist/lib/websocket.js:3:12)
    at WebSocket.<anonymous> (file:///var/home/gbonneville/src/pikatorrent/packages/node/dist/lib/websocket.js:20:35)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/var/home/gbonneville/src/pikatorrent/packages/node/node_modules/ws/lib/websocket.js:1184:20) {
  code: 'ERR_SET_REMOTE_DESCRIPTION'
}
```

**Comment by G-Ray** [comment]
remote control is not a planned feature from v0.10.0
